# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(308, 367)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(110, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.Candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Candidate_label.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.Candidate_label.setObjectName("Candidate_label")
        self.ID_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(60, 60, 21, 21))
        self.ID_label.setObjectName("ID_label")
        self.John_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.John_radio.setGeometry(QtCore.QRect(90, 140, 82, 17))
        self.John_radio.setObjectName("John_radio")
        self.jake_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jake_radio.setGeometry(QtCore.QRect(90, 160, 82, 17))
        self.jake_radio.setObjectName("jake_radio")
        self.Submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit_button.setGeometry(QtCore.QRect(90, 210, 75, 23))
        self.Submit_button.setObjectName("Submit_button")
        self.VoteConfirmation_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.VoteConfirmation_label.setGeometry(QtCore.QRect(20, 240, 221, 21))
        self.VoteConfirmation_label.setText("")
        self.VoteConfirmation_label.setObjectName("VoteConfirmation_label")
        self.VoteTotals_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.VoteTotals_label.setGeometry(QtCore.QRect(20, 260, 231, 21))
        self.VoteTotals_label.setText("")
        self.VoteTotals_label.setObjectName("VoteTotals_label")
        self.ID_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.ID_input.setObjectName("ID_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 308, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Application"))
        self.title_label.setText(_translate("MainWindow", "Voting"))
        self.Candidate_label.setText(_translate("MainWindow", "Candidates"))
        self.ID_label.setText(_translate("MainWindow", "ID"))
        self.John_radio.setText(_translate("MainWindow", "John Doe"))
        self.jake_radio.setText(_translate("MainWindow", "Jake Longe"))
        self.Submit_button.setText(_translate("MainWindow", "Submit vote"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
